### ISSUE TITLE
What Wrong?

### ISSUE THREAD

**Issue by zhiephie** [aaronplanell/create-react-app-calculator#2]
`TypeError: _reactPoint2.default is undefined`

**Comment by aaronplanell** [comment]
Hi @zhiephie !

Have you tried to launch 'npm install react-point'? I use the 1.0.2 version.
Another thing, make a pull before. I made a commit two minutes ago.

Best regards!

**Comment by aaronplanell** [comment]
Sorry. I have a problem with this versions (returns a warning). The last one, developed by @mjackson, have no warnings with the calculator.

**Comment by zhiephie** [comment]
Hi @aaronplanell, Thanks for replay. 

No, I'm not install with npm install react-point, and I try downgrade use the 1.0.2 version, return same.

**Comment by aaronplanell** [comment]
Please, try with a new installation. It works for me:

```
git clone https://github.com/aaronplanell/create-react-app-calculator.git
cd create-react-app-calculator
npm install
npm start
```

**Comment by zhiephie** [comment]
Oke work it @aaronplanell
